# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, unique=True)),
                ('ppics', models.ImageField(default='products/default.jpg', upload_to='products/images')),
                ('pintro', models.CharField(max_length=50)),
                ('pshortdesc', models.CharField(max_length=500)),
                ('pdesc', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pproj',
            field=models.ManyToManyField(to='deaspo.Project'),
        ),
        migrations.AddField(
            model_name='product',
            name='prel',
            field=models.ManyToManyField(blank=True, related_name='_product_prel_+', to='deaspo.Product'),
        ),
    ]
