# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Web'), ('B', 'Desktop'), ('C', 'Mobile'), ('D', 'Others')], default='Web', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdesc',
            field=models.TextField(default='Product description', max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='pintro',
            field=models.CharField(default='Brief intro', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(default='Product', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ppics',
            field=models.ImageField(default='D:/Users\\polyc/PycharmProjects/deaspo_inc/deaspo/media/products/default.jpg', upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pshortdesc',
            field=models.CharField(default='Short description', max_length=500),
        ),
    ]
