# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0002_auto_20161112_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pmain',
            field=models.BooleanField(default=False),
        ),
    ]
