# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 09:51
from __future__ import unicode_literals

import deaspo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0003_product_pmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_name', models.CharField(max_length=50, unique=True)),
                ('pn_monthly', models.DecimalField(decimal_places=2, default=5, max_digits=3)),
                ('SSD', models.IntegerField(default=20)),
                ('Transers', models.IntegerField(default=1)),
                ('Ram', models.IntegerField(default=512)),
                ('CPU', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='ppics',
            field=models.ImageField(default='D:/Users\\polyc/PycharmProjects/deaspo_inc/deaspo/media/products/default.jpg', upload_to=deaspo.models.path_file_name),
        ),
        migrations.AddField(
            model_name='product',
            name='plan',
            field=models.ManyToManyField(to='deaspo.Plan'),
        ),
    ]
