# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:10
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0004_auto_20161123_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_ename', models.CharField(max_length=50, unique=True)),
                ('pn_eprice', models.DecimalField(decimal_places=2, default=5, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWebOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Cannot be less than 1!')])),
                ('hosting_plan', models.CharField(max_length=50)),
                ('backup', models.BooleanField(default=False)),
                ('wed_design', models.BooleanField(default=True)),
                ('web_design_name', models.CharField(blank=True, max_length=50)),
                ('domain', models.BooleanField(default=True)),
                ('domain_name', models.CharField(max_length=50)),
                ('custom_email', models.BooleanField(default=False)),
                ('custom_email_name', models.CharField(blank=True, max_length=50)),
                ('custom_email_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Negatives not allowed')])),
                ('dedicated_inbox', models.BooleanField(default=False)),
                ('dedicated_inbox_plan', models.CharField(blank=True, max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Negatives not allowed')])),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_no', models.IntegerField()),
                ('contact_address', models.TextField(max_length=1000)),
                ('notes', models.TextField(max_length=1000)),
                ('acceptance_terms', models.BooleanField(default=True)),
                ('posted_date', models.DateTimeField(default=datetime.datetime(2016, 11, 23, 16, 10, 57, 330000), editable=False)),
            ],
        ),
    ]
