# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0006_auto_20161123_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='pn_yearly',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 19, 16, 30, 26, 958000), editable=False),
        ),
    ]
