# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-21 21:08
from __future__ import unicode_literals

import datetime
import deaspo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deaspo', '0007_auto_20161219_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Self-personal'), ('B', 'Company'), ('C', 'Contractor'), ('D', 'Others')], default='Company', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(default='D:/Users/polyc/PycharmProjects/deaspo_inc/deaspo/media/profile.png', upload_to=deaspo.models.path_profile_image)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='ppics',
            field=models.ImageField(default='D:/Users/polyc/PycharmProjects/deaspo_inc/deaspo/media/products/default.jpg', upload_to=deaspo.models.path_file_name),
        ),
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 22, 0, 8, 28, 795000), editable=False),
        ),
    ]
