# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-23 04:47
from __future__ import unicode_literals

import datetime
import deaspo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0009_auto_20161223_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 23, 7, 47, 26, 695000), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='D:/Users/polyc/PycharmProjects/deaspo_inc/deaspo/media/profile.png', upload_to=deaspo.models.path_profile_image),
        ),
    ]
