# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-24 07:02
from __future__ import unicode_literals

import datetime
import deaspo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deaspo', '0011_auto_20161223_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2016, 12, 24, 10, 2, 15, 403000))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 24, 10, 2, 15, 401000), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='D:/Users/polyc/PycharmProjects/deaspo_inc/deaspo/media/profile.png', upload_to=deaspo.models.path_profile_image),
        ),
    ]
