# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-24 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0012_auto_20161224_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 24, 12, 14, 42, 448000), editable=False),
        ),
        migrations.AlterField(
            model_name='usernext',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 24, 12, 14, 42, 449000)),
        ),
    ]
