# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 12:24
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0015_auto_20161227_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pic',
            field=models.ImageField(default='D:/Users/polyc/PycharmProjects/deaspo_inc/deaspo/static/images/profile.png', upload_to='comments_images'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Cannot be less than 0'), django.core.validators.MaxValueValidator(limit_value=5, message='Max value allowed is 5')]),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='First comment', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 27, 15, 23, 9, 848000), editable=False),
        ),
        migrations.AlterField(
            model_name='usernext',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 27, 15, 23, 9, 849000)),
        ),
    ]
