# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-02 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0018_auto_20161228_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_email', models.EmailField(max_length=254)),
                ('cl_name', models.CharField(max_length=100)),
                ('cl_message', models.TextField(default='Your Message', max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 16, 36, 19, 975000), editable=False),
        ),
        migrations.AlterField(
            model_name='usernext',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 16, 36, 19, 976000)),
        ),
    ]
