# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-02 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0019_auto_20170102_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 16, 41, 51, 401000), editable=False),
        ),
        migrations.AlterField(
            model_name='usernext',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 16, 41, 51, 402000)),
        ),
    ]
