# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-02 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0020_auto_20170102_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Facebook'), ('B', 'Twitter'), ('C', 'Instagram'), ('D', 'Google Plus')], default='Facebook', max_length=50)),
                ('Link to profile', models.URLField()),
                ('s_class', models.CharField(default='wow fadeInDown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(default='profile.png', upload_to='staff/images')),
                ('about', models.TextField(max_length=1000)),
                ('position', models.CharField(choices=[('A', 'Developer'), ('B', 'Product Manager'), ('C', 'Director, Sales Operations'), ('D', 'Senior Developer'), ('B', 'Account Manager'), ('E', 'Visual Designer'), ('F', 'Manager, Product Design'), ('G', 'Company Lawyer'), ('H', 'Director, Sales Operations'), ('I', 'Manager, Marketing'), ('J', 'Business Analyst'), ('K', 'Community Director'), ('L', 'Chief Executive Officer'), ('M', 'Director, Customer Support'), ('N', 'Data Center Manager')], default='Developer', max_length=50)),
                ('joined', models.DateTimeField(auto_now=True)),
                ('social', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='deaspo.Social')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='cl_message',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 21, 3, 21, 276000), editable=False),
        ),
        migrations.AlterField(
            model_name='usernext',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 2, 21, 3, 21, 277000)),
        ),
    ]
