# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 06:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0025_auto_20170108_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='dname',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='pn_yearly',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productweborder',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 9, 32, 54, 55000), editable=False),
        ),
        migrations.AlterField(
            model_name='usernext',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 9, 32, 54, 56000)),
        ),
    ]
