# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0027_auto_20170110_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_mobile_android',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='product',
            name='p_mobile_windows',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.ManyToManyField(blank=True, to='deaspo.Plan'),
        ),
    ]
