# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-21 21:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaspo', '0030_desktoporders'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosting_plan', models.CharField(max_length=100)),
                ('hosting_start_price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Negatives not allowed')])),
                ('fname', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('zcode', models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Enter the correct code'), django.core.validators.MaxLengthValidator(limit_value=5, message='Enter the correct code'), django.core.validators.MinValueValidator(limit_value=0, message='Cannot be negative')])),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('A', 'Kenya'), ('B', 'Others')], default='Kenya', max_length=100)),
                ('pnumber', models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Enter the correct code'), django.core.validators.MaxLengthValidator(limit_value=10, message='Enter the correct code'), django.core.validators.MinValueValidator(limit_value=0, message='Cannot be negative')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email address')])),
            ],
        ),
    ]
